### ISSUE TITLE
[server] Add support for Materialized Views 

### ISSUE THREAD

**Issue by Extra-lightwill** [MachineAcuity/rebar#271]
Very cool that this boilerplate now supports SASI indexes :) 

I've seen that you've closed the issue re: SASI indexes and materialized views - I'm just interested to know whether you have plans to add support for materialized views to this boilerplate in the near future.

I'm still convinced that a Cassandra app requires materialized views for proper data modelling...

The information under the first header of this blog article [](http://www.doanduyhai.com/blog/?p=1930 ) by  a datastax Cassandra evangelist (Duhay Doan) gives reasons as to why you might want materialized views (even though you can achieve similar data operations with SASI indexes). 

I don't know how long it would take to integrate into URB or how much effort it would be, but would definitely be a good addition imo.

P.S. Express Cassandra also provides support for materialized views too!

**Comment by thelordoftheboards** [comment]
Indeed maybe I should have cloned the issue and closed it, or renamed it. Either way, materialized views are still something that would need to be done, so let's use this issue to track that. Link to previous discussion about materialized views:

https://github.com/codefoundries/UniversalRelayBoilerplate/issues/248

**Comment by Extra-lightwill** [comment]
Don't know if this was added or I missed it first time around but I've been re-reading the Express-Cassandra docs and it seems that there is in-built support for Materialized Views. 

http://express-cassandra.readthedocs.io/en/latest/find/ 

**Find (querying a materialized view)**
And if you have defined materialized views in your schema as described in the schema detail section, then you can query your views by using the similar find/findOne functions. Just add an option with the materialized view name like the following:

```
models.instance.Person.find({name: 'John'}, { materialized_view: 'view_name1', raw: true }, function(err, people){
    //people is an array of plain objects taken from the materialized view
});
```

http://express-cassandra.readthedocs.io/en/latest/schema/ Materialized views 

materialized_views provides you the ability to define cassandra 3.x materialized views for your model table. You may want to read more about it on the materialized view documentation. This is generally suited for querying high cardinality fields. If you need to use select * for the materialized view, you can also use select: ['*'].

Haven't tested it yet but I assume this will work right off the bat?

**Comment by thelordoftheboards** [comment]
My experience with SASI indexes and express-cassandra was completely hands off - I just defined them according to the instructions, and they just worked.
My hope would be that the same would apply to materialized views. If you have the time, please feel free to add an example to URB, it would be interesting to have a good example for others who are trying to use this boilerplate.

**Comment by Extra-lightwill** [comment]
Great, when I get chance I will add a full example.

**Comment by thelordoftheboards** [comment]
@Extra-lightwill have you had a chance to work on this? Would any new features in 3.10 make life easier in regard to materialized views?

**Comment by thelordoftheboards** [comment]
Support coming in the next major update.

**Comment by thelordoftheboards** [comment]
Current version features usage of materialized views over secondary indexes exclusively.
