### ISSUE TITLE
[documentation] Describe sample production setup

### ISSUE THREAD

**Issue by querl** [MachineAcuity/rebar#446]
How to run the new boilerplate correctly in a production environment?
Thanks for a hint.

**Comment by thelordoftheboards** [comment]
We are currently building a set of tools for managing releases and deployment through ansible. The project is available here:

https://github.com/codefoundries/rebar-tools

However, it is unfinished and will probably be finished in the beginning of 2018. Feel free to read the scripts though.

In the meantime you can use:

```bash
yarn build-deployment
```

and then run the server from a copy of the `deployment` directory by using

```bash
node server/server
```

Is this helpful? What other information do you need?

**Comment by querl** [comment]
Yes, thanks. I assume I have to set the production env like `export NODE_ENV=production && node deployment/units/core/server/server`

**Comment by thelordoftheboards** [comment]
Yes that should be what you need, plus, of course, change all the appropriate settings in `.env`

**Comment by thelordoftheboards** [comment]
@querl have you succeeded in running it?

**Comment by querl** [comment]
Sorry for the late answer. unfortunately not, not even with the current master branch of URB. I run into some problems with missing UserToken2. I have not solved the problem yet. 

My steps

1. git pull 
2. yarn && yarn setup-local
3. set JWT_SECRET and SESSION_SECRET in _configuration/default.env
4. yarn build-deployment
5. export NODE_ENV=production && node deployment/units/urb-base-server/server
6. check localhost:260005 / {}:26005

error in client.js -> Uncaught (in promise) TypeError: Cannot read property 'data' of null (UserToken2)

<img width="1264" alt="screen shot 2017-12-11 at 18 38 49" src="https://user-images.githubusercontent.com/739165/33845100-9914e1e2-dea2-11e7-9c21-4638ee3f006a.png">

thanks for any hint!

**Comment by thelordoftheboards** [comment]
Unfortunate. I will attempt to replicate it as soon as I have time.

**Comment by thelordoftheboards** [comment]
@querl please try this sequence.

Run:

```
git clone https://github.com/codefoundries/UniversalRelayBoilerplate.git
cd UniversalRelayBoilerplate/
yarn
```

Set `JWT_SECRET` and `SESSION_SECRET` in `.env` in the project root. Run:

```
yarn setup-local
yarn build-deployment
yarn update-ip 127.0.0.1
cp .env deployment/.env
export NODE_ENV=production && node deployment/units/urb-base-server/server
```

Browse to the `127.0.0.1:26005`.

Works on my machine. Hope that works for you too. Naturally, the IP would be the IP of your server probably sitting behind Nginx, but I changed it to localhost for simplicity and reproduce-ability.

**Comment by querl** [comment]
@thelordoftheboards I can confirm, it works now perfectly. Thanks!

**Comment by thelordoftheboards** [comment]
Excellent. I will add this to the readme and keep the issue open until its not done.

**Comment by querl** [comment]
@thelordoftheboards Just for your information. My problem was `yarn update-ip` I did not set my localhost ip as you discribed (`yarn update-ip 127.0.0.1`), so the .env file was updated with my internal lan ip like 192.186.0.44 and that caused the js error on my mac dev machine.

**Comment by thelordoftheboards** [comment]
Interesting ..... I guess for simplicity I will just publish instructions for using 127.0.0.1 since it should always work. As for specific deployment they would vary a lot.
Having a docker instance would be cool but I don't have the time to build it right now.

**Comment by thelordoftheboards** [comment]
https://github.com/MachineAcuity/rebar#production
