### ISSUE TITLE
[server] Update cassandra-driver to 3.6.0

### ISSUE THREAD

**Issue by oboz** [MachineAcuity/rebar#476]
Please update cassandra-driver to 3.6.0, because express-cassandra use this version in current time. And in result boilerplate have problems with validation of UUID

**Comment by thelordoftheboards** [comment]
@oboz, thank you. Looking into it. Unfortunately upgrading to 3.6 is causing multiple issues.

**Comment by thelordoftheboards** [comment]
I was able to update after deleting yarn-lock. I don't have a reasonable explanation as to why exactly it did not work before, but seems to be working well now.
